version: "3.9"

networks:
  progimage-network:
    external: true

services:
  bcgdv-service:
    container_name: "bcgdv-progimage-service"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:${PORT}
    networks:
      - progimage-network
