# Generated by Django 4.0.5 on 2022-06-19 09:42

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformedimage',
            name='transformed_file',
            field=models.ImageField(max_length=255, upload_to=api.utils.image_upload_path),
        ),
    ]
